### ISSUE TITLE
Use data from file?

### ISSUE THREAD

**Issue by Ismoh** [kenloen/plotly.lua#2]
Is there a way to use the data (x,y) from a file, instead having all the coordinates in memory?

**Comment by kenloen** [comment]
Do you mean streaming data from a file? In that case I think it is going to be difficult with the current implementation as you would need to have a server running - you might be better of using JS for that. You could use https://fengari.io/ to have LUA load your data.

If you mean making multiple plots out of the same data file while would would need to make a partial data loading in LUA and save each plot.

**Comment by Ismoh** [comment]
I am using this repo for easy plotting with plotly in lua, but the problem is, that the software (a game with only 2gb memory available) throws out of memory, when data is too big. That's why I was thinking to simply write the data in json format into a json file, which is then used when creating the html file.

Kinda like a second lua method slightly different. But I am not aware yet how to define it in JS to use a json file. If I'll find anything, I would create a PR. Do you know some resources/references?

**Comment by Ismoh** [comment]
I think [this](https://towardsdatascience.com/how-to-use-plotly-js-for-data-visualization-46933e1bbd29) in combination with an additional function and slightly changes on [this](https://github.com/kenloen/plotly.lua/blob/main/plotly.lua#L191-L194) should work. Not sure if plotly.d3.json can handle local files or if it has to be a url.

**Comment by Ismoh** [comment]
I found a way to write traces into files and simply import them into the html without any server running. It's kinda ugly, but I need a fast way to plot things without any overhead. Going to create a PR the next days. Take a look and if you like it merge it. If not close it. Thanks !
